/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.alex73.voice.splitter;

/**
 *
 * @author alex
 */
public class VoiceSplitterFrame extends javax.swing.JFrame {

    /**
     * Creates new form VoiceSplitterFrame
     */
    public VoiceSplitterFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        split = new javax.swing.JSplitPane();
        scroll = new javax.swing.JScrollPane();
        panelList = new javax.swing.JPanel();
        panelAudio = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        bDec = new javax.swing.JButton();
        bInc = new javax.swing.JButton();
        bPlay = new javax.swing.JButton();
        bPrev = new javax.swing.JButton();
        bNext = new javax.swing.JButton();
        bSplit = new javax.swing.JButton();
        bMerge = new javax.swing.JButton();
        bForceSplit = new javax.swing.JButton();
        cbFiles = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miStat = new javax.swing.JMenuItem();
        miSave = new javax.swing.JMenuItem();
        miExport = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        miUndo = new javax.swing.JMenuItem();
        miRedo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Voice Splitter");

        split.setDividerLocation(300);
        split.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        split.setResizeWeight(0.8);

        scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scroll.setViewportView(panelList);

        split.setLeftComponent(scroll);

        panelAudio.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        bDec.setText("-");
        bDec.setFocusable(false);
        bDec.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bDec.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(bDec, gridBagConstraints);

        bInc.setText("+");
        bInc.setFocusable(false);
        bInc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bInc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(bInc, gridBagConstraints);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("messages"); // NOI18N
        bPlay.setText(bundle.getString("BUTTON_PLAY")); // NOI18N
        bPlay.setFocusable(false);
        bPlay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bPlay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(bPlay, gridBagConstraints);

        bPrev.setText(bundle.getString("BUTTON_PREV")); // NOI18N
        bPrev.setFocusable(false);
        bPrev.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bPrev.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(bPrev, gridBagConstraints);

        bNext.setText(bundle.getString("BUTTON_NEXT")); // NOI18N
        bNext.setFocusable(false);
        bNext.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bNext.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(bNext, gridBagConstraints);

        bSplit.setText(bundle.getString("BUTTON_SPLIT_TEXT")); // NOI18N
        bSplit.setFocusable(false);
        bSplit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bSplit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(bSplit, gridBagConstraints);

        bMerge.setText(bundle.getString("BUTTON_MERGE_NEXT")); // NOI18N
        bMerge.setFocusable(false);
        bMerge.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bMerge.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(bMerge, gridBagConstraints);

        bForceSplit.setText("Force split");
        bForceSplit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(bForceSplit, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(cbFiles, gridBagConstraints);

        jLabel1.setText(bundle.getString("BUTTON_MOUSE")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(jLabel1, gridBagConstraints);

        panelAudio.add(jPanel1, java.awt.BorderLayout.NORTH);

        split.setRightComponent(panelAudio);

        getContentPane().add(split, java.awt.BorderLayout.CENTER);

        jMenu1.setText(bundle.getString("MENU_PROJECT")); // NOI18N

        miStat.setText(bundle.getString("MENU_STATISTICS")); // NOI18N
        jMenu1.add(miStat);

        miSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        miSave.setText(bundle.getString("MENU_SAVE")); // NOI18N
        jMenu1.add(miSave);

        miExport.setText(bundle.getString("MENU_EXPORT")); // NOI18N
        jMenu1.add(miExport);

        jMenuBar1.add(jMenu1);

        menuEdit.setText(bundle.getString("MENU_EDIT")); // NOI18N

        miUndo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        miUndo.setText(bundle.getString("AbstractUndoableEdit.redoText")); // NOI18N
        menuEdit.add(miUndo);

        miRedo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        miRedo.setText(bundle.getString("AbstractUndoableEdit.undoText")); // NOI18N
        menuEdit.add(miRedo);

        jMenuBar1.add(menuEdit);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VoiceSplitterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VoiceSplitterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VoiceSplitterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VoiceSplitterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VoiceSplitterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bDec;
    public javax.swing.JButton bForceSplit;
    public javax.swing.JButton bInc;
    public javax.swing.JButton bMerge;
    public javax.swing.JButton bNext;
    public javax.swing.JButton bPlay;
    public javax.swing.JButton bPrev;
    public javax.swing.JButton bSplit;
    public javax.swing.JComboBox<AudioFileComboItem> cbFiles;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JMenu menuEdit;
    public javax.swing.JMenuItem miExport;
    public javax.swing.JMenuItem miRedo;
    public javax.swing.JMenuItem miSave;
    public javax.swing.JMenuItem miStat;
    public javax.swing.JMenuItem miUndo;
    public javax.swing.JPanel panelAudio;
    public javax.swing.JPanel panelList;
    public javax.swing.JScrollPane scroll;
    public javax.swing.JSplitPane split;
    // End of variables declaration//GEN-END:variables
}
